version: '3.9'
services:
  database:
    image: mysql:8
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_tourism_password
        MYSQL_DATABASE: tourism
        MYSQL_USER: customer
        MYSQL_PASSWORD_FILE: /run/secrets/db_tourism_password
    networks:
        - local-network
    secrets:
        - db_root_tourism_password
        - db_tourism_password
    ports:
        - "${LOCAL_DB_PORT:-3306}:${DOCKER_DB_PORT:-3306}"
    volumes: 
        - ./database/initdb.d:/docker-entrypoint-initdb.d
        - tourism-data:/var/lib/mysql
  # backend-update:
  #   depends_on:
  #     - database
  #   build: ./backend-update
  #   restart: always
  #   environment:
  #       DB_NAME: tourism
  #       DB_USERNAME: customer
  #       # PORT: ${DOCKER_DB_UPDATE_PORT:-8080}
  #   volumes:  
  #       - ./backend-update/app:/app
  #   networks:
  #       - local-network
  #   secrets:
  #       - db_tourism_password
  #       - app_id
  #       - app_key
  #   ports: 
  #       - "${LOCAL_DB_UPDATE_PORT:-8080}:${DOCKER_DB_UPDATE_PORT:-8080}"
  backend:
    depends_on:
      - database
    build: ./backend
    restart: always
    environment:
        DB_NAME: tourism
        DB_USERNAME: customer
        PROCESS_NUM: 4
        PORT: ${DOCKER_SERVER_PORT:-8080}
    volumes:  
        - ./backend/app:/app
    networks:
        - local-network
    secrets:
        - db_tourism_password
        - app_id
        - app_key
    ports: 
        - "${LOCAL_SERVER_PORT:-8080}:${DOCKER_SERVER_PORT:-8080}"
  frontend:
    depends_on:
      - backend
    build: ./frontend
    environment:
        PORT: ${DOCKER_NGINX_PORT:-80}
        REACT_APP_API_HOST_NAME: ${REACT_APP_API_HOST_NAME}
    volumes:
      - ./frontend/app/build:/usr/share/nginx/html
      - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports: 
      - "${LOCAL_NGINX_PORT:-80}:${DOCKER_NGINX_PORT:-80}"
    restart: always
secrets:
    db_root_tourism_password:
      file: secrets/db_root_tourism_password
    db_tourism_password:
      file: secrets/db_tourism_password
    app_id:
      file: secrets/app_id
    app_key:
      file: secrets/app_key
networks:
  local-network:
    driver: bridge
volumes:
  tourism-data: